name: feeling_finder
description: A fast and beautiful app to help convey emotion in text communication.

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 1.1.0+16

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  collection: ^1.17.1
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_flatpak:
    git:
      url: https://github.com/Merrit/flutter_flatpak.git
      ref: d443e0fcb8f74f844cb39f822a0193ec43e64a4f
  flutter_localizations:
    sdk: flutter
  freezed_annotation: ^2.2.0
  google_fonts: ^4.0.4
  helpers:
    git:
      url: https://github.com/Merrit/helpers.git
      ref: cf08d198e9cefe6556ffb5d389e29ca14d32408a
  hid_listener: ^1.1.2
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  hotkey_manager: ^0.1.8
  http: ^1.0.0
  json_annotation: ^4.8.1
  logger: ^1.3.0
  package_info_plus: ^4.0.1
  path_provider: ^2.0.6
  pub_semver: ^2.1.4
  tutorial_coach_mark: ^1.2.8
  unicode_emojis: ^0.3.0
  url_launcher: ^6.1.11
  window_manager: ^0.3.2
  window_size:
    git:
      url: https://github.com/google/flutter-desktop-embedding.git
      path: plugins/window_size
      ref: 03d957e8b5c99fc83cd4a781031b154ab3de8753

dev_dependencies:
  bloc_test: ^9.1.0
  build_runner: ^2.4.4
  flutter_app_builder:
    git:
      url: https://github.com/Merrit/flutter_app_builder.git
      ref: 07f12157ace33c062b7611cfbbb41ec67a897eb6
  flutter_launcher_icons: ^0.10.0
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  freezed: ^2.3.4
  integration_test:
    sdk: flutter
  json_serializable: ^6.7.0
  mockito: ^5.4.1
  msix: ^3.6.6

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/icons/
    - assets/images/

# To generate icons run:
# flutter pub run flutter_launcher_icons:main
flutter_icons:
  android: true
  ios: false
  image_path: "assets/icons/codes.merritt.FeelingFinder.png"

flutter_app_builder:
  app_display_name: "Feeling Finder"
  author: "Merritt Codes"
  identifier: codes.merritt.FeelingFinder
  msix_identity_name: codes.merritt.FeelingFinder
  msix_publisher: CN=0AA9BC0E-36DF-4B4F-BFF4-E300B746CB9D
  msix_icon_path: assets\icons\codes.merritt.FeelingFinder.png
  msix_capabilities: internetClient
