name: feeling_finder
description: A fast and beautiful app to help convey emotion in text communication.

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 0.8.2+14

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_flatpak:
    git:
      url: https://github.com/Merrit/flutter_flatpak.git
      ref: d443e0fcb8f74f844cb39f822a0193ec43e64a4f
  flutter_localizations:
    sdk: flutter
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  logger: ^1.3.0
  path_provider: ^2.0.6
  rich_clipboard: ^1.0.1
  window_size:
    git:
      url: https://github.com/google/flutter-desktop-embedding.git
      path: plugins/window_size
      ref: 03d957e8b5c99fc83cd4a781031b154ab3de8753

dev_dependencies:
  flutter_launcher_icons: ^0.10.0
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  mocktail: ^0.3.0
  msix: ^3.6.6

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/icon/
    - assets/images/

# To generate icons run:
# flutter pub run flutter_launcher_icons:main
flutter_icons:
  android: true
  ios: false
  image_path: "assets/icon/icon.png"

# Config for the msix Windows installer.
msix_config:
  display_name: Feeling Finder
  publisher_display_name: Kristen McWilliam
  identity_name: codes.merritt.feelingfinder
  msix_version: 1.0.0.0
  logo_path: assets\icon\icon.png
  capabilities: ""
