name: feeling_finder
description: A fast and beautiful app to help convey emotion in text communication.

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 1.7.0+27

homepage: https://github.com/Merrit/feeling_finder

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  collection: ^1.17.1
  dbus: ^0.7.10
  device_info_plus: ^10.1.2
  easy_debounce: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_flatpak:
    git:
      url: https://github.com/Merrit/flutter_flatpak.git
      ref: d443e0fcb8f74f844cb39f822a0193ec43e64a4f
  flutter_localizations:
    sdk: flutter
  freezed_annotation: ^2.2.0
  google_fonts: ^6.2.1
  helpers:
    git:
      url: https://github.com/Merrit/helpers.git
      ref: 804cf94cda4b7003740fdb0c3e30909d31c2fb18
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  hotkey_manager: ^0.2.3
  http: ^1.0.0
  intl: ^0.19.0
  json_annotation: ^4.8.1
  logger: ^2.0.1
  package_info_plus: ^8.0.2
  path_provider: ^2.0.6
  pub_semver: ^2.1.4
  slang: ^3.22.0
  slang_flutter: ^3.22.0
  tray_manager: ^0.2.2
  tutorial_coach_mark: ^1.2.8
  unicode_emojis: ^0.4.0
  url_launcher: ^6.1.11
  window_manager: ^0.4.2
  window_size:
    git:
      url: https://github.com/google/flutter-desktop-embedding.git
      path: plugins/window_size
      ref: 6c66ad23ee79749f30a8eece542cf54eaf157ed8

dev_dependencies:
  bloc_test: ^9.1.0
  build_runner: ^2.4.4
  flutter_app_builder:
    git:
      url: https://github.com/Merrit/flutter_app_builder.git
      ref: a70df0728d9d7d8fd528553ff7d88be01a789a38
  flutter_gen: ^5.3.1
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.3.4
  integration_test:
    sdk: flutter
  json_serializable: ^6.7.0
  mockito: ^5.4.1
  msix: ^3.16.7
  slang_build_runner: ^3.22.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    - assets/fonts/
    - assets/icons/
    - assets/images/

# To generate icons run:
# flutter pub run flutter_launcher_icons
flutter_icons:
  android: true
  ios: false
  image_path: "assets/icons/codes.merritt.FeelingFinder.png"

flutter_app_builder:
  app_display_name: "Feeling Finder"
  author: "Merritt Codes"
  identifier: codes.merritt.FeelingFinder
  languages:
    - en-us
    - de
    - it
    - pt
    - pt-br
    - ru
  msix_identity_name: 33694MerrittCodes.FeelingFinder
  msix_publisher: CN=0AA9BC0E-36DF-4B4F-BFF4-E300B746CB9D
  msix_icon_path: assets\icons\codes.merritt.FeelingFinder.png
  msix_capabilities: internetClient
