name: feeling_finder
description: A fast and beautiful app to help convey emotion in text communication.

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 0.5.0+10

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^7.3.3
  flutter_localizations:
    sdk: flutter
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  mocktail: ^0.2.0
  path_provider: ^2.0.6
  window_size:
    git:
      url: https://github.com/google/flutter-desktop-embedding.git
      path: plugins/window_size
      ref: 03d957e8b5c99fc83cd4a781031b154ab3de8753

dev_dependencies:
  flutter_launcher_icons: ^0.9.2
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  msix: ^2.8.18

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/

# To generate icons run:
# flutter pub run flutter_launcher_icons:main
flutter_icons:
  android: true
  ios: false
  image_path: "assets/images/icon.png"

# Config for the msix Windows installer.
msix_config:
  display_name: Feeling Finder
  publisher_display_name: Kristen McWilliam
  identity_name: codes.merritt.feelingfinder
  msix_version: 1.0.0.0
  logo_path: assets\images\icon.png
  capabilities: ""
