name: feeling_finder
description: A fast and beautiful app to help convey emotion in text communication.

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.15.0-178.1.beta <3.0.0"

dependencies:
  dbus: ^0.6.3
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^7.3.3
  flutter_localizations:
    sdk: flutter
  hive: ^2.0.4
  mocktail: ^0.2.0
  path_provider: ^2.0.6

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
