name: update_flatpak_recipe
description: A simple command-line application.
version: 1.0.0
# homepage: https://www.example.com
environment:
  sdk: ">=2.17.0-69.2.beta <3.0.0"

dependencies:
  github: ^9.0.0
  intl: ^0.17.0
  xml: ^5.3.1

dev_dependencies:
  lints: ^1.0.0
