display_name: Feeling Finder
package_name: feeling-finder
maintainer:
  name: Merrit
  email:
priority: optional
section: x11
installed_size: 27859
essential: false
icon: assets/icons/codes.merritt.FeelingFinder.png

#pre_dependencies:
#  - libc6 (>= 2.31)

dependencies:
  - libkeybinder-3.0-0
  - libappindicator3-1
  - libayatana-appindicator3-1
  - libayatana-ido3-0.4-0

#postinstall_scripts:
#  - echo "Feeling Finder Installed!"
#postuninstall_scripts:
#  - echo "Sorry to see you go 😞"

keywords:
  - Emojis
  - Ease of Use

generic_name: A fast and beautiful app to help convey emotion in text communication.

categories:
  - GTK
  - Utility
  - Amusement

startup_notify: true