name: Release Android to Google Play

on:
  # Enable manual run
  workflow_dispatch:
  # Build & deploy for published releases
  release:
    types:
      - published

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Download .aab artifact
        run: |
          wget https://github.com/Merrit/feeling_finder/releases/latest/download/FeelingFinder-Android.aab

      - name: Access Google Play API key
        env:
          GOOGLE_PLAY_API_JSON: ${{ secrets.GOOGLE_PLAY_API_JSON }}
        run: |
          echo "$GOOGLE_PLAY_API_JSON" | base64 --decode > google_play_api.json

      - name: Release Android build on Google Play
        uses: r0adkll/upload-google-play@v1.0.15
        with:
          serviceAccountJson: google_play_api.json
          packageName: codes.merritt.FeelingFinder
          releaseFiles: *.aab
          track: production
