name: Run tests

on:
  # Allow being called by other workflows
  workflow_call:
  # Allow being called manually
  workflow_dispatch:

jobs:
  flutter_test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2

      - name: Setup
        run: |
          flutter pub get

      - name: Verify formatting
        run: dart format -o none --set-exit-if-changed --line-length=100 .

      - name: Run code generation
        run: flutter pub run build_runner build --delete-conflicting-outputs

      - name: Run lint
        run: flutter analyze

      - name: Run tests
        run: flutter test
