name: Run tests

on:
  # Allow being called by other workflows
  workflow_call:
  # Allow being called manually
  workflow_dispatch:

jobs:
  flutter_test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2.10.0

      - name: Setup
        run: |
          flutter upgrade
          flutter pub get

      - name: Verify formatting
        run: dart format -o none --set-exit-if-changed .

      - name: Run code generation
        run: flutter pub run build_runner build --delete-conflicting-outputs

      - name: Run i18n generation
        run: flutter gen-l10n

      - name: Run lint
        run: flutter analyze

      - name: Run tests
        run: flutter test

  integration_tests_linux:
    name: Run integration tests on Linux
    runs-on: ubuntu-latest
    needs: flutter_test
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2.10.0

      - name: Setup requirements for integration tests
        run: |
          sudo apt-get update -y
          sudo apt-get install -y clang ninja-build libgtk-3-dev xvfb
          # libappindicator required for tray_manager
          sudo apt-get install -y libappindicator3-dev
          # keybinder required for global hotkeys
          sudo apt-get install -y keybinder-3.0

      - name: Setup Flutter
        run: |
          flutter upgrade
          flutter pub get

      - name: Run code generation
        run: flutter pub run build_runner build --delete-conflicting-outputs

      - name: Run i18n generation
        run: flutter gen-l10n

      - name: Run integration test on Linux
        run: xvfb-run -a flutter test -d linux integration_test -v
